#/run/numberOfThreads 8
/run/initialize

/run/verbose 0

/control/alias EGap 15     # Electrodes Gap
/control/alias TM   1.5e-3 # Thickness Membrane 1.5um
/control/alias TE   5.0e-5 # Thickness Electrode 50nm
/control/alias EO   0      # Offset of each lateral Anode 0 
/control/alias nS   32     # Number of Electrode strips 32 
/control/alias SE   70     # Sides length of Electrode

# -- Fission Product Source
# =========================
/gps/pos/type     Plane
/gps/pos/shape    Circle
/gps/pos/centre   0 0 22.5031 mm #= -EGap/2-TM-TE-EGap-TE-TM
/gps/pos/radius   30 mm
/gps/pos/sigma_r  3 mm
/gps/ang/type     cos
/gps/ang/mintheta 0.00000 rad
/gps/ang/maxtheta 0.00001 rad
/gps/ang/minphi   0.00000 rad
/gps/ang/maxphi   0.00001 rad

/gps/particle proton
/gps/ene/type Mono
/gps/ene/mono 68 MeV

# -- RUN W/ Analysis Manager
# ==========================

# -------------------------
/score/create/boxMesh      boxMesh
/score/mesh/boxSize        {SE}/2 {SE}/2 {TM}/2 mm
/score/mesh/nBin           {nS} {nS} 1
/score/mesh/translate/xyz  0 0 -{EGap}/2-{TM}-{TE}-{EGap}-{TE}-{TM}/2 mm
/score/quantity/cellFlux   M1_flux

/score/close
/score/list

/run/beamOn 10

/score/dumpQuantityToFile boxMesh M1_flux M1_flux.dat

























